### ISSUE TITLE
ld: file is universal (2 slices) but does not contain a(n) armv7 slice: /Users/jayzhao/Dev/buffer-ios-sdk/BufferSDK/libBufferSDK.a for architecture armv7 clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by ghost** [bufferapp/buffer-ios-sdk#1]
ld: file is universal (2 slices) but does not contain a(n) armv7 slice: /Users/jayzhao/Dev/buffer-ios-sdk/BufferSDK/libBufferSDK.a for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ay8s** [comment]
Sorry about that @JayZhao. I've just updated it and it should now contain all 3 slices.

**Comment by ghost** [comment]
Thank you @ay8s for fixing that!
