### ISSUE TITLE
Buffer activity doesn't show up in UIActivityViewController

### ISSUE THREAD

**Issue by ghost** [bufferapp/buffer-ios-sdk#3]
Hi,

I've come up with some issues in the latest 1.1.6 version of the SDK.

With initWithActivityItems:items:
Items are a string, an image, a URL and NSData.
Buffer failed to show up. I have to include NSData there because there are other activities using this.

But if I delete the NSData buffer shows up with blank icon in UIActivityViewController.

**Comment by ay8s** [comment]
@JayZhao That's a good one, i'll take a look into this and see if we can get an update put up to resolve this along with the missing icon you're seeing.

**Comment by ay8s** [comment]
Should have a new version of the SDK tomorrow which resolves this and includes some new functionality @JayZhao.

**Comment by ghost** [comment]
@ay8s Thats great! Thank you!

**Comment by ay8s** [comment]
Should be fixed now @JayZhao :)
