### ISSUE TITLE
[BMBProgressHUD show:] called in secondary thread

### ISSUE THREAD

**Issue by ghost** [bufferapp/buffer-ios-sdk#4]
Hi,

I don't know if this is a bug...

It seems [BMBProgressHUD show:] is not called on main thread (which should be?).

Here's the stack:
![screen shot 2013-10-04 at 11 02 19 pm](https://f.cloud.github.com/assets/2278174/1270195/0a8e9668-2d06-11e3-9db2-893c2c6e7164.png)

**Comment by ay8s** [comment]
Hmm, i'll check this out @JayZhao and get back to you on it. Were the other issues you were seeing all fixed up?

**Comment by ghost** [comment]
@ay8s yes, the icon is back and the Buffer activity is showing up again now. Thank you!

**Comment by ay8s** [comment]
@JayZhao This should be resolved in 1.2.4. Let me know if you spot anything else.

Thanks again for pointing things out. :+1:
