### ISSUE TITLE
Please build the framework for 64bit devices too.

### ISSUE THREAD

**Issue by VilemKurz** [bufferapp/buffer-ios-sdk#6]
I have set Architectures to "standard architectures (including 64bit)" and deployment target to 5.1.1. 

The error is Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_BufferSDK", referenced from:
      objc-class-ref in libShareKit.a(SHKBuffer.o)

**Comment by VilemKurz** [comment]
see https://github.com/ShareKit/ShareKit/issues/820

**Comment by ay8s** [comment]
This was completed recently, although shifting our focus over to a App Extension for iOS 8.
